spring.application.name=spring-ai-demo
spring.ai.google.genai.api-key=AIzaSyArFnh4nscVV11iPNYKBVS3DZOLO3Z9dI8
spring.ai.google.genai.api-version=v1
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
